// Module included in the following assemblies:
//
// * networking/networking_operators/dpf_operator/dpf-worker-nodes-provisioning.adoc

:_mod-docs-content-type: PROCEDURE
[id="nw-dpf-enabling-ovnk-resource-injector_{context}"]
= Enable the OVN-Kubernetes resource injector

[role="_abstract"]
You can install the OVN-Kubernetes resource injector by using Helm to deploy a mutating webhook that automatically injects SR-IOV virtual function resource requests and network attachment annotations into each pod scheduled to a worker node.

[NOTE]
====
Virtual function resource capacity on worker nodes is provided by the `NodeSRIOVDevicePluginConfig` resource, which replaces the manual SR-IOV device plugin `DaemonSet` and control plane node patching used in earlier DPF versions.
====

.Prerequisites

* You have access to the management cluster as a user with the `cluster-admin` role.
* You have installed the `oc` CLI.
* You have installed the `helm` CLI.
* You have set the DPF Operator environment variables. For details, see "DPF Operator installation environment variables".
* You have created the `NodeSRIOVDevicePluginConfig` resource.

.Procedure

. Install the OVN-Kubernetes resource injector by using Helm:
+
[source,terminal]
----
$ helm install ovn-kubernetes-resource-injector \
  $OVN_TEMPLATE_CHART_URL/ovn-kubernetes-chart \
  --namespace openshift-ovn-kubernetes \
  --version ${OVN_CHART_VERSION} \
  --skip-crds \
  --set ovn-kubernetes-resource-injector.enabled=true \
  --set resourceName=openshift.io/bf3-p0-vfs \
  --set nodeWithDPUManifests.enabled=false \
  --set nodeWithoutDPUManifests.enabled=false \
  --set dpuManifests.enabled=false \
  --set controlPlaneManifests.enabled=false \
  --set commonManifests.enabled=false \
  --wait
----
+
[NOTE]
====
The `--skip-crds` flag prevents conflicts with OVN-Kubernetes CRDs already managed by the Cluster Network Operator.
====
+
.Example output
[source,terminal]
----
NAME: ovn-kubernetes-resource-injector
LAST DEPLOYED: Sun Nov  2 17:10:29 2025
NAMESPACE: openshift-ovn-kubernetes
STATUS: deployed
REVISION: 1
TEST SUITE: None
----

.Verification

* Verify the resource injector mutating webhook configuration was applied:
+
[source,terminal]
----
$ oc get mutatingwebhookconfiguration | grep ovn
----
+
.Example output
[source,terminal]
----
NAME                                                    WEBHOOKS   AGE
ovn-kubernetes-resource-injector                        1          22h
----
